name: SpecFlow.Pipeline.Error

on: 
  push:
    paths-ignore:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.402' # SDK Version to use.
      - name: Restore
        run: dotnet restore
      - run: dotnet test SpecFlow.Tests/SpecFlow.Tests.csproj